---
output:
  html_document:
    fig_width: 9
    toc: yes
    toc_float: yes
---

```{r, echo=FALSE}
tutblog <- read.csv("qianyu_tutblogs.csv", encoding = "UTF-8")
selection<-tutblog[tutblog$name=="Microsoft Excel shortcuts",]
```
`r paste0("# ",selection$name)`
`r paste0("### *by ",selection$authors,"*")`

<div class = "row">
<div class = "col-md-9">`r paste0("*started ",selection$date," and updated ",format(Sys.Date(), '%Y-%m-%d'),"*")`</div>

<br/>

# Intro
Recently, I am using Microsoft Excel to work on data analysis. I will recommend some powerful and useful shortcuts i know to you guys. All right, let's get the ball rolling. 

# Shortcuts

**Extend selection** - Control + Shift + arrow keys

**Fill down** - Control + D to copy values from the cell above without copy paste

**Autosum** - Alt + =

**Go to first cell/last cell** - Control + Home / Control + End

**Data navigation** - Control + arrow keys

**Fill handle** - Double click the little square at the bottom right of any selection

**New table** - Control + T

**Close the new window** - Control + W to close the dumplicate view of excel file

**Select non-adjacent data for a plot/chart** - [Shift + F8](http://www.office68.com/excel/23485.html) 

# References
[20 very popular Excel shortcuts](https://exceljet.net/blog/20-very-popular-excel-shortcuts)

