---
title: "Stories in life"
author:  "[Qianyu Hang](https://github.com/hangqianyu) at NC State University"
date: '`r format(Sys.Date(), "%a %b %d, %Y")`'
output:
  html_document:
    out_height: 0.1
    out_width: 0.1
---

------------

* The insightful saying i personally like:

**"Not everything that counts can be counted and not everything that's counted truly counts"**  - By Albert Einstein
<br/><br/><br/>

* The poem i personally like:

**The Road Not Taken** - by *Robert Frost*

Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth;

Then took the other, as just as fair,

And having perhaps the better claim,

Because it was grassy and wanted wear;

Though as for that the passing there

Had worn them really about the same,

And both that morning equally lay

In leaves no step had trodden black.

Oh, I kept the first for another day!

Yet knowing how way leads on to way,

I doubted if I should ever come back.

I shall be telling this with a sigh

Somewhere ages and ages hence:

Two roads diverged in a wood, and I—

I took the one less traveled by,

And that has made all the difference.

# Intro

To date, there are hundreds and thousands challenges in my life during almost each period from middle school to now as a PhD student. You can never imagine what you will look like tomorrow. So i will make this part as a "diary" to document what i went through since now.

# May 20, 2018
I am not good at hydraulics and statistics. But what i am doing now is about hydraulics and statistics. Sometimes, I questioned myself if i should go for a PhD abroad in this area rather soon after graduating from CRAES. Would that be better if i work for several years to gain experience in related areas? Yeah, i have to tell myself i thought too much. People also tell me everyone can face challenges in their life, and you are not exceptional either. To face the truth, i was learning how to use R Studio for data analysis, R markdown for nice documentation, Github for co-working on a same project effectively and make a personal website. And now, i am considering to read more literature regarding stream restoration. First literature is Chiao-Wen's dissertation. I hope i can make a progress soon.

# May 21, 2018
Today, i thought if i can focus my research a bit to water quality rather than hydrology or uncertainty research like what Chiao-Wen did? Then, it would definitely make my research easier because i will be supposed to learn statistics and basic hydrology. But how to form a structure of whole PhD dissertation is still a question? Chiao-Wen actually proved that new optical based sensors/UV-Vis can be applied in the low gradient streams of the coastal plain of North Carolina. She also tested the uncertainties on measuring the cumulative loads associated with the data generated by UV-Vis spectrophotomaters and provide guidelines for robust sampling strategies. And the cost of continuous measuring only proported 4%-10% in total costs. 




















