---
output:
  html_document:
    toc: yes
    toc_float: yes
link-citation: yes
bibliography: Bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
tutblog <- read.csv("research_tutblogs.csv", encoding = "UTF-8")
selection<-tutblog[tutblog$name=="Controversial voices among the effects of stream restoration call for evaluation of robust indicators",]
```
`r paste0("# ",selection$name)`
`r paste0("### *by ",selection$authors,"*")`

<div class = "row">
<div class = "col-md-9">`r paste0("*started ",selection$date," and updated ",format(Sys.Date(), '%Y-%m-%d'),"*")`</div>

<br/>

---------
# Abstract
  A growing number of stream restoration projects have been undertaken to counteract the adverse effects of stream degradation worldwide. Nevertheless, controversies on the real impacts of stream restoration still exist. The objective of this paper is to review the current knowledge base on the impacts of stream restoration in water quality, hydromorphology and fish/invertebrate community. Based on the database developed in this study, 67% of projects indicated a positive effect of nitrogen reduction following restoration. Hydromorphological improvements were identified almost by all hydromorphological restoration efforts. As fish/invertebrate community require a long time-frame to recover, reaching common ground can therefore be difficult due to different time-frames applied by researchers. Given that restoration studies are usually site- and approach-specific, it is impossible to predict every outcome of a stream restoration project by simply extrapolating the results from one single study. However, finding some robust indicators for which could show the uniform trend following restoration is helpful for evaluating the effectiveness of stream restoration projects. Several future research needs should be highlighted: 1) implement high-resolution data analysis, in particular for water quality; 2) choose robust indicators for restoration project evaluation; and 3) avoid comparison using nearby reference streams.
  
# Keywords:
Stream restoration; Water quality; Hydromorphology; Biotic communities

# 1. Introduction
A nationwide investigation found that among 16% assessments of 3.5 million stream miles in the United States in 2004, 44% of them were identified as impaired or polluted [@RN1820]. Countless streams had highly altered flows or were geomorphically degraded [@RN1823]. Over the last two decades, growing public sensitivity toward environmental degradation and scientific awareness of the ecological and biological importance of water quality and hydromorphological diversity in streams have driven numerous attempts to recover degraded systems [@RN1857; @RN1846]. Stream restoration, an effort to reshape "more complex ecosystems from more simple and degraded states" [@RN1813], is a relatively young science and has been considered as a major enterprise, with most focusing on benthic invertebrates, fish population or geomorphic channel stability in the United States [@RN1826; @RN1827; @RN1824]. An average of more than $1 billion a year were spent on stream and river restoration in the US [@RN1814].  

However, early in the 1990s, [-@RN1815] stated that many "walking aways" from restoration projects after construction without systematic monitoring forfeited the investment if the project failed and prevented the next generation of projects from benefiting from the effort if the project was successful. For instance, [-@RN1822] quantified and summarized pre-restoration data on water quality, pesticides concentrations, chlorophyll a, physical in-stream habitat, and biotic community (fish analysis) from the project on Gypsum Creek in Wichita, Kansas. They indicated a potential improvement of stream water quality, physical habitat, and biotic integrity by stream restoration. However, no further publications on the overall effects of stream restoration have been seen probably due to lack of further funding from the state and local management agencies, or literally no effects at all.

Yet, researchers have been trying to quantify the effects of stream restoration with respect to: i) water quality, ii) hydromorphology, iii) riparian zones connection, iv) in-stream habitat, and v) biotic communities. There were five commonly stated goals in the US based on the National River Restoration Science Synthesis (NRRSS) database [@RN1814]. Controversial voices have still been around debating whether stream restoration is worthwhile or not [@RN1821]. Each individual study can show important characteristics and combining them, as performed in this review, can help illustrate trends. The objective of this paper was to review the current knowledge base on the impacts of stream restoration in water quality, hydromorphology, and biotic communities and can also identify future research needs.

# 2. Stream Restoration Goals
To date, there has been a substantial amount of publications on stream restoration. A dramatic increase of publications containing keywords, either 'stream restoration' or 'stream restoration effects', was observed since the 1990s from google scholar searching (include patents) (Fig. 1).

## 2.1 Water Quality
Water quality improvement was often listed as an ancillary goal of restoration efforts [@RN1814; @RN1831]. Recommendations for stream restoration on water quality improvements should not proceed without a thorough assessment to determine if measurable water quality benefits exist following restoration. Although restoration may include numerous individual manipulations, each with the potential to alter ecosystem or in-stream processes [@RN1834], potential increases in nitrate removal existed if stream restoration could contribute to connecting stream reaches with riparian zones or increasing stream hydrologic residence time [@RN1835]. Previous work on impacts of stream restoration in water quality were summarized in Table 1.

[-@RN1841] suggested that potential denitrification rates could be increased by building organic debris dams in streams, which might be challenging in urban streams because high storm flows and flashiness could easily destroy debris dams [@RN1842]. Therefore, building the organic debris dams is not practical in flooding or high rainfall areas.[-@RN1840] indicated a potential improvement for water quality by iterating pre-restoration data from Minebank Run stream in Baltimore County, Maryland. Later, after implementation of restoration, higher average denitrification rates were observed in the restored streams compared to unrestored streams [@RN1828]. Increased hydrologic interaction with organic-rich soils underlying well-developed vegetation in riparian zones, can stimulate higher denitrification rates at the riparian-zone-stream interface [@RN1833].

Not only denitrification rates but also stream nutrient uptake can be affected by stream restoration since hydrological, geomorphological, and biological characteristics can be altered, thus influencing in-stream nitrogen transformation processes [@RN1839; @RN1837; @RN1838]. For example, coarse woody debris was added to disturbed streams for increasing hydrodynamic and structural complexity, with the goals of enhancing biotic habitat and increasing nutrient uptake rates [@RN1832]. Ammonium uptake rates increased both in controls and restored streams at the Fort Benning Military Installation near Columbus, Georgia. Promoting dissimilative uptake of nitrogen or denitrification is the most common goal for restoration that target nitrogen reduction because it leads to the permanent removal of nitrogen from the system [@RN1828; @RN1829]. Different forms of nitrogen must be considered in restoration efforts since a fundamental condition for denitrification to occur is availability of nitrate [@RN1830]. Additionally, focusing on lowering nitrogen inputs to the streams will in the long run be more likely to provide nutrient reduction and other restoration benefits than only focusing on in-stream nutrient removal processes.

However, not all researchers reported restoration being efficient for nitrogen reduction. [-@RN1823] assessed the effectiveness of restored streams positioned in the upland (Bristol, Moreland, and Mall) versus lowland (Spa Creek, Howard's Branch, and Wilelinor) regions of Coastal Plain watershed during both average and stormflow conditions. Only those converted lowland streams converted to stream-wetland complexes were effective at reducing nitrogen fluxes during periods of high flow, while no clear evidence supported that upland streams reduced nitrogen export during any hydrological conditions. This might indicate stream restoration does little or even no help to water quality improvements without combining wetland systems within the 3-year time-frame in the Coastal Plain region of western Maryland. Another example of integrated stream/wetland ecosystem working efficiently in stream nitrogen and phosphorus reduction was that [@RN1843]. They observed 64% and 28% attenuation of nitrite-N + nitrate-N and TP, respectively, after deploying an integrated stream/wetland restoration approach to hydrologically reconnect the stream with the adjacent floodplain in Upper Sandy Creek, a headwater stream for the Cape Fear River in the North Carolina Piedmont. These results agreed with points made by some researchers that stream restoration alone was not appropriate for substantial nitrate removal and should be viewed as a complementary method because of uncertainties concerning the magnitude and range of possible nitrate removal [@RN1836; @RN1828].

Based on literature review, a few publications target water quality improvements by stream restoration because of missing pre-restoration/post-restoration data, negative/no effects observed, or little attention on water quality benefits at all. Conflicting reports on whether stream restoration helped enhance water quality call for systematic and standard evaluation of restoration projects. Several reasons might explain those controversies: 1) a short time-frame monitoring was inadequate to demonstrate water quality benefits [@RN1844]; 2) large uncertainties resulting from low-resolution data limited the iteration of real effects of stream restoration [@RN1819]; 3) effects of restoration practices are site-specific [@RN1847]; 4) different restoration approaches applied in the research [@RN1846]; and/or 5) inconsistent/un-robust indicators utilized for evaluation.

### Table 1. Impacts of stream restoration on water quality.
     
## 2.2 Hydromorphology

In large parts of Central Europe, particularly in the lowlands of Germany and the Netherlands, the hydromorphology of up to 90% of streams were severely degraded [@RN1854; @RN1853]. Widespread among these impacts were a variety of physical, including straightening, embanking, degrading, and removal of large woody debris that homogenize the hydromorphological features of the channel [@RN1856]. Uniform channels with low substrate diversity, low current variability and low depth variability could result from, for instance, straightening. The hydromorphological improvements of stream restoration, though often noted, are rarely studied and quantified [@RN1852]. Therefore, efforts on documenting hydromorphological changes of stream restoration were summarized (Table 2). Conceptual support arised from the theory which stated that hydromorpholigical heterogeneity provides resource gradients along which functionally similar species can segregate and thus coexist [@RN1858]. Despite the conceptual support, empirical evaluations of the relation between restoration and hydromophological indexes in streams have produced conflicting results (Table 2).

The MIKE SHE hydrological model of a 2.3 km2 meadow along a 3.6 km restored reach of Bear Creek in the northeastern California was developed [@RN1851]. Three positive hydrological responses to the meadow restoration effort were identified: 1) increased groundwater levels and volume of subsurface storage; 2) increased frequency/duration of floodplain inundation and decreased magnitude of flood peaks, and 3) decreased annual runoff and duration of baseflow. One year later experimental data from two restored streams in Gartroper Muhlenbach and Schwalm, German, also suggested that restoration had contributed to wider stream reaches, near-natural channel features and increase in hydromorphological variability [@RN1852]. Also, [-@RN1859] stated that hydromorphological heterogeneity for restored streams represented a distinct recovery gradient compared to unrestored status. These results are a clear distinction between degraded and restored reaches. However, [-@RN1856] assessed hydromorphological heterogeneity at the tributaries of the Ume river in northern Sweden using a contour tracer at two spatial resolutions: the patch scale (0.7 m), reflecting substratum characteristics; and the reach scale (50 m), reflecting general channel topography. Although they reported a substantially higher structural heterogeneity at restored reaches than at channelized sites, no significant differences of heterogeneity were observed between restored and nearby reference streams [@RN1856]. This could be caused by the large uncertainties associated with comparison to nearby reference streams [@RN1819]. 

Unlike water quality, hydromorphological indexes seem to be respond quicker to the restoration. Improved and non-uniformed hydromorphology could contribute to a more diverse environment for growing the number and species of fish and macroinvertebrate populations.
    
## 2.3 Biotic Communities

Stream ecosystems across the world are subject to multiple impacts, including pollution, regulation, water abstraction, canalization, gravel mining, or bank reinforcement for flood protection [@RN1860]. As a result, many streams have been transformed from dynamically active and spatially complex ecosystems to more static and homogenous systems, resulting in large decreases in biodiversity and altered ecosystem functioning [@RN1861]. Recently, many projects aimed at restoring stream fish and invertebrates habitat by re-creating critical habitat features or by removing barriers to dispersal [@RN1860; @RN1862]. Summarizing the current work on restoring stream habitat for improvement of biotic communities is likely to benefit future research (Table 3).

For example. the total number of macroinvertebrate families, genera, and taxa were significantly higher in re-meandered reaches of both Gartroper Muhlenbach (10-year restored) and Schwalm streams (2-year restored). However, replicate results provided a contradictory perspective: much lower abundance of macroinvertebrate families, genera, and taxa were reported in the shortly restored reach of Gartroper Muhlenbach [@RN1852]. [-@RN1855] noted a recovery leading to higher densities of macroinvertebrates in the subsequent years after a decreased densities trend were observed shortly following restoration. Thus, the decrease observed in the study of [-@RN1852] could be explained by macroinvertebrate communities needing more time to adapt than hydromorphological indexes. 

Interestingly, confounded conclusions were reported in some studies themselves. Large woody debris introduced into four mountain streams in the Aiako Harria Natural Park (Basque County, Spain) did not have much impact on fish densities, but greatly increased fish biomass [@RN1860]; biomass decreased with increasing stream size with a trend towards more aged 2+ or larger, thus suggesting wood addition improved adult habitat. Negligible effects were observed for invertebrate metrics with implementation of a small scale habitat restoration [@RN1827].

Instead of coming to confused conclusions, [-@RN1851] claimed negligible effects were obtained within twenty-six pairs of 9-year restored streams in Austria, Czech Republic, Germany, Italy, and Netherlands either using passive or active restoration approaches. 

Large-scale habitat restoration was recommended for a recovery of the invertebrate community by [-@RN1827]; however, large-scale habitat restoration was demonstrated to be less efficient in recovering fish densities and biomass than the small-scale ones due to woody debris loss from the large environment [@RN1860]. The effects of restoration projects cannot simply be extrapolated to the entire stream networks worldwide since the restoration practices were site-specific studies. It is rather impossible to predict the outcome of a stream habitat restoration for biotic community biodiversity due to the dynamic nature of ecosystems, and in particular streams [@RN1844]. Consequently, stream habitat restoration can provide a template for enhancement of biotic communities, but the dynamic nature and the individuality of the stream will finally determine the results [@RN1863]. Therefore, how we benefit from previous restoration efforts is becoming more and more important.

### Table 3. Impacts of stream restoration on biotic communities.

# 3 Future research needs

From previous work, a common approach to quantify water quality benefits was to compare discrete sample concentrations and corresponding instantaneous loads over short and discontinuous periods of time [@RN1819]. Large uncertainties stated by numerous authors are likely to confound the effects of stream restoration [@RN1864]. The recent availability of continuous optical sensors, ultraviolet-visual spectrophotometers for water quality has opened the possibility to obtain high-resolution water quality data which can reveal concentration dynamics that were not unveiled until now [@RN1865].High-resolution data analysis could fill the gap between each discrete sampling, reducing uncertainties and making it possible to quantify the real effects of stream restoration.

Still, comparing pre- and post- restoration was implied to be robust enough to characterize and compare each phase. However, selecting indicators or parameters for estimating the real effects of restoration could never be more important since it avoids meaningless and wrong comparisons. Some indicators suggested by [-@RN1819] include stream bank stability or macroinvertebrate and fish populations, physical, hydromorphological and biochemical conditions in streams, like channel width, water depth, discharge, current velocity. These indicators are theoretically robust to indicate significant differences between pre- and post- restoration.

It is reasonable to draw a conclusion from comparison of restored and unrestored streams with similar conditions. Interestingly, there seems to be many researchers using nearby reference streams as the control system for comparison. Separate streams can never be fully comparable due to non-identical conditions between those streams [@RN1819].

# 4 Conclusion

There is little consensus on whether stream restoration can improve water quality and biotic communities, while a large portion of studies agreed that hydromorphological benefits can be achieved. Nitrogen reduction via denitrification and ammonium uptake is always the focus among studies regarding water quality benefits of stream restoration. Nitrogen forms in streams should be thoroughly understood before restoration design because different restoration approaches target different forms of nitrogen reduction. Generally, hydromorphological improvements were indicated by most of studies to date and could be observed shortly, like several months, after restoration. Long-term monitoring was recommended and required for obtaining significant enhancement of fish/invertebrate densities, biomass and diversity. It remains difficult to say that by implementing restoration what is the benefit to water quality/hydromorphology/fish and invertebrate communities, since restoration studies are usually site- and approach-specific. However, each individual study can show important characteristics and combining them can help inspire new insights. Several future research needs exist: 1) implement high-resolution data analysis, in particular for water quality; 2) choose robust indicators for restoration project evaluation; and 3) avoid comparison using nearby reference streams.

# References